package com.example.util

import android.content.Context
import android.content.Intent
import android.graphics.Canvas
import android.graphics.Color
import android.graphics.Paint
import android.graphics.RectF
import android.graphics.pdf.PdfDocument
import android.net.Uri
import android.os.Environment
import android.widget.Toast
import androidx.core.content.FileProvider
import com.example.model.ComplianceStatus
import com.example.model.InspectionRecord
import com.example.model.UserProfile
import com.example.model.UserRole
import java.io.File
import java.io.FileOutputStream
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale

object PdfReportGenerator {

    /**
     * Generates a PDF file on local device storage and returns the created File.
     */
    fun generatePdfReport(
        context: Context,
        record: InspectionRecord,
        userProfile: UserProfile
    ): File? {
        val pdfDocument = PdfDocument()
        val pageWidth = 595 // Standard A4 width in points at 72 DPI
        val pageHeight = 842 // Standard A4 height in points at 72 DPI
        val pageInfo = PdfDocument.PageInfo.Builder(pageWidth, pageHeight, 1).create()
        val page = pdfDocument.startPage(pageInfo)
        val canvas: Canvas = page.canvas

        val paint = Paint().apply { isAntiAlias = true }
        val titlePaint = Paint().apply {
            isAntiAlias = true
            isFakeBoldText = true
        }

        var currentY = 36f
        val leftMargin = 36f
        val rightMargin = pageWidth - 36f
        val contentWidth = rightMargin - leftMargin

        // 1. Top Header Banner
        paint.color = Color.rgb(15, 23, 42) // Navy 900
        canvas.drawRect(0f, 0f, pageWidth.toFloat(), 64f, paint)

        // Header Title
        titlePaint.color = Color.rgb(245, 158, 11) // Gold accent
        titlePaint.textSize = 12f
        canvas.drawText("MINISTRY OF CONSUMER AFFAIRS • LEGAL METROLOGY DIRECTORATE", leftMargin, 26f, titlePaint)

        titlePaint.color = Color.WHITE
        titlePaint.textSize = 15f
        val isOfficer = userProfile.role == UserRole.OFFICER
        val docTitle = if (isOfficer) "OFFICIAL STATUTORY INSPECTION REPORT (FORM LM-IR)" else "PACKAGING COMPLIANCE & VERIFICATION REPORT"
        canvas.drawText(docTitle, leftMargin, 48f, titlePaint)

        currentY = 82f

        // 2. Inspection & User Info Box
        paint.color = Color.rgb(248, 250, 252) // Slate 50
        val infoBoxRect = RectF(leftMargin, currentY, rightMargin, currentY + 95f)
        canvas.drawRoundRect(infoBoxRect, 6f, 6f, paint)
        paint.color = Color.rgb(226, 232, 240) // Slate 200
        paint.style = Paint.Style.STROKE
        paint.strokeWidth = 1f
        canvas.drawRoundRect(infoBoxRect, 6f, 6f, paint)
        paint.style = Paint.Style.FILL

        val col1 = leftMargin + 12f
        val col2 = leftMargin + (contentWidth / 2f) + 6f
        var infoY = currentY + 18f

        // Row 1
        paint.color = Color.rgb(100, 116, 139)
        paint.textSize = 9f
        canvas.drawText("INSPECTION ID:", col1, infoY, paint)
        titlePaint.color = Color.rgb(15, 23, 42)
        titlePaint.textSize = 10f
        canvas.drawText(record.id, col1 + 80f, infoY, titlePaint)

        paint.color = Color.rgb(100, 116, 139)
        paint.textSize = 9f
        canvas.drawText("DATE & TIME:", col2, infoY, paint)
        val dateFormat = SimpleDateFormat("dd MMM yyyy, hh:mm a", Locale.getDefault())
        val dateStr = dateFormat.format(Date(record.timestamp))
        canvas.drawText(dateStr, col2 + 70f, infoY, titlePaint)

        infoY += 18f

        // Row 2
        paint.color = Color.rgb(100, 116, 139)
        paint.textSize = 9f
        val userLabel = if (isOfficer) "INSPECTING OFFICER:" else "GENERATED BY USER:"
        canvas.drawText(userLabel, col1, infoY, paint)
        canvas.drawText("${userProfile.name} (${userProfile.role.displayName})", col1 + 115f, infoY, titlePaint)

        paint.color = Color.rgb(100, 116, 139)
        paint.textSize = 9f
        val idLabel = if (isOfficer) "BADGE / ID:" else "USER ID:"
        canvas.drawText(idLabel, col2, infoY, paint)
        canvas.drawText(userProfile.id, col2 + 70f, infoY, titlePaint)

        infoY += 18f

        // Row 3
        paint.color = Color.rgb(100, 116, 139)
        paint.textSize = 9f
        canvas.drawText("LOCATION / STORE:", col1, infoY, paint)
        val storeLocation = "${record.storeName}, ${record.locationName}"
        val truncatedLoc = if (storeLocation.length > 32) storeLocation.take(30) + "..." else storeLocation
        canvas.drawText(truncatedLoc, col1 + 95f, infoY, titlePaint)

        paint.color = Color.rgb(100, 116, 139)
        paint.textSize = 9f
        canvas.drawText("FACILITY TYPE:", col2, infoY, paint)
        canvas.drawText(record.facilityType, col2 + 75f, infoY, titlePaint)

        infoY += 18f

        // Row 4: Category
        paint.color = Color.rgb(100, 116, 139)
        paint.textSize = 9f
        canvas.drawText("COMMODITY CATEGORY:", col1, infoY, paint)
        canvas.drawText(record.category.displayName, col1 + 120f, infoY, titlePaint)

        paint.color = Color.rgb(100, 116, 139)
        paint.textSize = 9f
        canvas.drawText("CATEGORY CODE:", col2, infoY, paint)
        canvas.drawText(record.category.name, col2 + 90f, infoY, titlePaint)

        currentY += 105f

        // 3. Compliance Summary Banner
        val statusBgColor = when (record.status) {
            ComplianceStatus.COMPLIANT -> Color.rgb(220, 252, 231) // Green 100
            ComplianceStatus.WARNING -> Color.rgb(254, 243, 199) // Amber 100
            ComplianceStatus.NON_COMPLIANT -> Color.rgb(254, 226, 226) // Red 100
        }
        val statusBorderColor = when (record.status) {
            ComplianceStatus.COMPLIANT -> Color.rgb(34, 197, 94)
            ComplianceStatus.WARNING -> Color.rgb(245, 158, 11)
            ComplianceStatus.NON_COMPLIANT -> Color.rgb(239, 68, 68)
        }
        val statusTextColor = when (record.status) {
            ComplianceStatus.COMPLIANT -> Color.rgb(22, 101, 52)
            ComplianceStatus.WARNING -> Color.rgb(146, 64, 14)
            ComplianceStatus.NON_COMPLIANT -> Color.rgb(153, 27, 27)
        }

        paint.color = statusBgColor
        val statusRect = RectF(leftMargin, currentY, rightMargin, currentY + 38f)
        canvas.drawRoundRect(statusRect, 6f, 6f, paint)
        paint.color = statusBorderColor
        paint.style = Paint.Style.STROKE
        paint.strokeWidth = 1.2f
        canvas.drawRoundRect(statusRect, 6f, 6f, paint)
        paint.style = Paint.Style.FILL

        titlePaint.color = statusTextColor
        titlePaint.textSize = 12f
        val statusTitle = "AUDIT STATUS: ${record.status.name}   |   SCORE: ${record.complianceScore}/100   |   VIOLATIONS: ${record.violations.size}"
        canvas.drawText(statusTitle, leftMargin + 14f, currentY + 24f, titlePaint)

        currentY += 48f

        // 4. Product Identification
        titlePaint.color = Color.rgb(30, 41, 59)
        titlePaint.textSize = 11f
        canvas.drawText("PRODUCT IDENTIFICATION", leftMargin, currentY, titlePaint)
        currentY += 6f
        paint.color = Color.rgb(203, 213, 225)
        canvas.drawLine(leftMargin, currentY, rightMargin, currentY, paint)
        currentY += 14f

        paint.color = Color.rgb(71, 85, 105)
        paint.textSize = 9.5f
        canvas.drawText("Product Name: ${record.productName}", leftMargin + 4f, currentY, paint)
        currentY += 13f
        canvas.drawText("Brand / Manufacturer: ${record.brandManufacturer}", leftMargin + 4f, currentY, paint)
        currentY += 18f

        // 5. Statutory Declarations Table
        titlePaint.color = Color.rgb(30, 41, 59)
        titlePaint.textSize = 11f
        canvas.drawText("MANDATORY STATUTORY DECLARATIONS (LMPC 2011)", leftMargin, currentY, titlePaint)
        currentY += 6f
        paint.color = Color.rgb(203, 213, 225)
        canvas.drawLine(leftMargin, currentY, rightMargin, currentY, paint)
        currentY += 10f

        // Table Header
        paint.color = Color.rgb(241, 245, 249)
        val tableHeaderRect = RectF(leftMargin, currentY, rightMargin, currentY + 16f)
        canvas.drawRect(tableHeaderRect, paint)

        titlePaint.color = Color.rgb(51, 65, 85)
        titlePaint.textSize = 8.5f
        canvas.drawText("STATUTORY PARAMETER", leftMargin + 6f, currentY + 11f, titlePaint)
        canvas.drawText("OBSERVED VALUE", leftMargin + 175f, currentY + 11f, titlePaint)
        canvas.drawText("RULE REF", leftMargin + 370f, currentY + 11f, titlePaint)
        canvas.drawText("STATUS", leftMargin + 440f, currentY + 11f, titlePaint)
        currentY += 18f

        paint.textSize = 8f
        for (field in record.extractedFields.take(8)) {
            val fieldName = if (field.fieldName.length > 28) field.fieldName.take(26) + "..." else field.fieldName
            val declaredVal = if (field.extractedValue.isBlank()) "NOT DETECTED" else if (field.extractedValue.length > 34) field.extractedValue.take(32) + "..." else field.extractedValue
            val isDetected = field.extractedValue.isNotBlank() && field.status != com.example.model.FieldStatus.NOT_DETECTED

            paint.color = Color.rgb(15, 23, 42)
            canvas.drawText(fieldName, leftMargin + 6f, currentY + 9f, paint)

            paint.color = if (isDetected) Color.rgb(30, 41, 59) else Color.rgb(220, 38, 38)
            canvas.drawText(declaredVal, leftMargin + 175f, currentY + 9f, paint)

            paint.color = Color.rgb(100, 116, 139)
            canvas.drawText(field.ruleReference, leftMargin + 370f, currentY + 9f, paint)

            titlePaint.textSize = 8f
            if (isDetected) {
                titlePaint.color = Color.rgb(22, 101, 52)
                canvas.drawText("VERIFIED", leftMargin + 440f, currentY + 9f, titlePaint)
            } else {
                titlePaint.color = Color.rgb(185, 28, 28)
                canvas.drawText("NON-COMPLIANT", leftMargin + 440f, currentY + 9f, titlePaint)
            }

            paint.color = Color.rgb(241, 245, 249)
            canvas.drawLine(leftMargin, currentY + 13f, rightMargin, currentY + 13f, paint)
            currentY += 15f
        }

        currentY += 10f

        // 6. Violations & Statutory Deficiencies (if any)
        if (record.violations.isNotEmpty()) {
            titlePaint.color = Color.rgb(185, 28, 28)
            titlePaint.textSize = 11f
            canvas.drawText("IDENTIFIED STATUTORY VIOLATIONS (${record.violations.size})", leftMargin, currentY, titlePaint)
            currentY += 6f
            paint.color = Color.rgb(254, 202, 202)
            canvas.drawLine(leftMargin, currentY, rightMargin, currentY, paint)
            currentY += 12f

            for (violation in record.violations.take(3)) {
                titlePaint.color = Color.rgb(153, 27, 27)
                titlePaint.textSize = 8.5f
                canvas.drawText("• ${violation.ruleNumber}: ${violation.ruleTitle} [${violation.severity.name}]", leftMargin + 6f, currentY, titlePaint)
                currentY += 11f

                paint.color = Color.rgb(71, 85, 105)
                paint.textSize = 7.5f
                val explanation = if (violation.explanation.length > 90) violation.explanation.take(87) + "..." else violation.explanation
                canvas.drawText("  Observed: ${violation.observedValue} | Required: ${violation.expectedRequirement}", leftMargin + 10f, currentY, paint)
                currentY += 10f
                canvas.drawText("  Details: $explanation", leftMargin + 10f, currentY, paint)
                currentY += 13f
            }
        } else {
            paint.color = Color.rgb(240, 253, 244)
            val noVioRect = RectF(leftMargin, currentY, rightMargin, currentY + 24f)
            canvas.drawRoundRect(noVioRect, 4f, 4f, paint)
            titlePaint.color = Color.rgb(22, 101, 52)
            titlePaint.textSize = 9f
            canvas.drawText("✓ No statutory violations identified under Legal Metrology (Packaged Commodities) Rules.", leftMargin + 10f, currentY + 15f, titlePaint)
            currentY += 32f
        }

        // 7. Official Sign-off & Verification Footer
        val footerY = pageHeight - 52f
        paint.color = Color.rgb(241, 245, 249)
        canvas.drawRect(0f, footerY - 14f, pageWidth.toFloat(), pageHeight.toFloat(), paint)

        titlePaint.color = Color.rgb(71, 85, 105)
        titlePaint.textSize = 7.5f
        canvas.drawText("Official Verification Record generated via Inspectra LM System • Tamper-evident digital signature.", leftMargin, footerY, titlePaint)
        canvas.drawText("Secured Record Hash: ${record.id.hashCode().toUInt().toString(16).uppercase()}-VERIFIED", leftMargin, footerY + 11f, titlePaint)

        pdfDocument.finishPage(page)

        // Save PDF to Documents / App Storage
        return try {
            val docsDir = context.getExternalFilesDir(Environment.DIRECTORY_DOCUMENTS) ?: context.filesDir
            if (!docsDir.exists()) docsDir.mkdirs()
            val sanitizedId = record.id.replace("/", "_").replace(" ", "_")
            val pdfFile = File(docsDir, "Inspection_Report_${sanitizedId}.pdf")
            val fos = FileOutputStream(pdfFile)
            pdfDocument.writeTo(fos)
            fos.flush()
            fos.close()
            pdfDocument.close()
            pdfFile
        } catch (e: Exception) {
            e.printStackTrace()
            pdfDocument.close()
            null
        }
    }

    /**
     * Shares the generated PDF file via Android Share Sheet to WhatsApp, Email, Drive, etc.
     */
    fun sharePdfReport(context: Context, pdfFile: File, record: InspectionRecord) {
        try {
            val uri: Uri = FileProvider.getUriForFile(
                context,
                "${context.packageName}.fileprovider",
                pdfFile
            )

            val shareIntent = Intent(Intent.ACTION_SEND).apply {
                type = "application/pdf"
                putExtra(Intent.EXTRA_STREAM, uri)
                putExtra(Intent.EXTRA_SUBJECT, "Legal Metrology Inspection Report - ${record.id}")
                putExtra(
                    Intent.EXTRA_TEXT,
                    "Official Legal Metrology Packaging Inspection Report for ${record.productName}.\nAudit Status: ${record.status.name} (Score: ${record.complianceScore}/100).\nInspection ID: ${record.id}"
                )
                addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION)
            }

            val chooser = Intent.createChooser(shareIntent, "Share Inspection Report")
            chooser.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK)
            context.startActivity(chooser)
        } catch (e: Exception) {
            Toast.makeText(context, "Sharing failed: ${e.localizedMessage}", Toast.LENGTH_LONG).show()
        }
    }

    /**
     * Opens the PDF locally using the system's default PDF viewer.
     */
    fun openPdfLocally(context: Context, pdfFile: File) {
        try {
            val uri: Uri = FileProvider.getUriForFile(
                context,
                "${context.packageName}.fileprovider",
                pdfFile
            )
            val viewIntent = Intent(Intent.ACTION_VIEW).apply {
                setDataAndType(uri, "application/pdf")
                addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION)
                addFlags(Intent.FLAG_ACTIVITY_NEW_TASK)
            }
            context.startActivity(viewIntent)
        } catch (e: Exception) {
            Toast.makeText(context, "PDF saved to: ${pdfFile.absolutePath}", Toast.LENGTH_LONG).show()
        }
    }
}
